### ISSUE TITLE
False positive: Detected usage of a non-sanitized input variable: $_POST

### ISSUE THREAD

**Issue by david-binda** [Automattic/VIP-Coding-Standards#112]
`wp_verify_nonce` should not produce Detected usage of a non-sanitized input variable error.

Eg.: `wp_verify_nonce( $_POST['my_modules_nonce'], 'metro_modules' )` is totally valid.

EDIT: should not even produce `Detected access of super global var $_POST, probably needs manual inspection.`

**Comment by GaryJones** [comment]
Is this something that would better be addressed upstream in WPCS?
Or is it from code in VIPCS?

**Comment by GaryJones** [comment]
> Feels like it might be better addressed upstream.

https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/1508
