### ISSUE TITLE
Flag INPUT_SERVER and INPUT_ENV along with filter_input

### ISSUE THREAD

**Issue by david-binda** [Automattic/VIP-Coding-Standards#115]
For same reasons as mentioned in https://github.com/xwp/stream/issues/254

**Comment by GaryJones** [comment]
Is this any different to #222? The PHP bug was for 5.4, but with VIP running a much later version, is this still applicable?

**Comment by GaryJones** [comment]
Closing for lack of feedback. Can be re-opened if feedback arrives and it's still something that should be flagged.
