### ISSUE TITLE
Flag when parameters are passed to wpcom_vip_file_get_contents() without encoding them

### ISSUE THREAD

**Issue by gudmdharalds** [Automattic/VIP-Coding-Standards#129]

**Comment by david-binda** [comment]
Thanks for opening the issue @gudmdharalds ! Would you have an example of a code which needs to get caught?

**Comment by GaryJones** [comment]
And also example code that shouldn't get reported.

**Comment by GaryJones** [comment]
Closing for lack of feedback. Can be re-opened if feedback arrives and it's still something that should be flagged.
