### ISSUE TITLE
Flag window.location instances for manual review

### ISSUE THREAD

**Issue by david-binda** [Automattic/VIP-Coding-Standards#139]
`window.location.href`, `window.location.search` and possibly others bits should be considered being user input. Similarly to `$_GET` , `$_POST`, and `$_REQUEST` variables in PHP, those should be flagged for manual inspection.

**Comment by rogertheriault** [comment]
window.location, window.location.*, window.name, window.status all should be flagged.

**Comment by david-binda** [comment]
One example of vulnerable code would be:

```
var c=window.location.hash.split("#")[1];
...
document.write("<script src=\"//example.com.js?param=\""+c+"\">\x3c/script>");
```

The problem is that 1) `window.location.hash.split("#")[1]` is not validated / non sanitised when it's assigned to `c`, and 2) `c` is not escaped on output.

Only the case 1) is what should be part of this ticket - however catching 2) would also be great, if we are not doing so yet. Regarding the validation/sanitisation, an ideal sniff would act similarly to what `WordPress.VIP.ValidatedSanitizedInput` sniff would flag for:

```
$c = $_GET['c'];
```

> Detected usage of a non-validated input variable: $_GET (WordPress.VIP.ValidatedSanitizedInput.InputNotValidated)
> Detected usage of a non-sanitized input variable: $_GET (WordPress.VIP.ValidatedSanitizedInput.InputNotSanitized)

**Comment by rebeccahum** [comment]
2) is already caught by both our concatenation and `.write()` sniff I believe.

@GaryJones So I guess variable assignments are a use case for the sniff then?

**Comment by GaryJones** [comment]
> So I guess variable assignments are a use case for the sniff then?

I'd say so. Once it's assigned to the variable, PHPCS won't be able to follow how _that_ variable is being used, so we'd have to flag at the point of the assignment, at least as a warning.
