### ISSUE TITLE
Flag iframe buster files that have known vulnerabilities

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/VIP-Coding-Standards#154]
Lots of iframe buster files for ads have known vulnerabilities - we should maintain a blacklist and scan for their code.

**Comment by GaryJones** [comment]
@nickdaugherty 	Can you please give an example / more context to this?

**Comment by GaryJones** [comment]
Closing for lack of feedback. Can be re-opened if feedback arrives and it's still something that should be flagged.
