### ISSUE TITLE
Catch incorrect usage of esc_attr__()

### ISSUE THREAD

**Issue by gudmdharalds** [Automattic/VIP-Coding-Standards#155]
For instance:

```
 <a href="..."><?php echo esc_attr__( 'testing', 'mytheme' ); ?> </a>
```

**Comment by GaryJones** [comment]
We [check](https://github.com/Automattic/VIP-Coding-Standards/blob/develop/WordPressVIPMinimum/Sniffs/Security/ProperEscapingFunctionSniff.php#L90-L94) if `esc_html()` is being used in an attribute, but we don't check if `esc_attr()` (or the variants) are being used outside of an attribute.
