### ISSUE TITLE
Catch usage of the_sub_field()

### ISSUE THREAD

**Issue by gudmdharalds** [Automattic/VIP-Coding-Standards#156]
`the_sub_field()` (part of Advanced Custom Fields) does not escape output -- we should catch usage of this function and warn that the output will go out unescaped.

See: https://github.com/elliotcondon/acf/blob/master/core/api.php#L681

**Comment by gudmdharalds** [comment]
Same applies to `the_field()`: https://github.com/elliotcondon/acf/blob/master/core/api.php#L329

**Comment by rebeccahum** [comment]
Closing per #248
