### ISSUE TITLE
Unused variable

### ISSUE THREAD

**Issue by sboisvert** [Automattic/VIP-Coding-Standards#166]
Should we remove this or mark it Warning level 2?

**Comment by rebeccahum** [comment]
I vote to remove it in an effort to reduce the noise on SRs.

**Comment by sboisvert** [comment]
What if we run the Standard review at 5 and leave it in for informational so folks can have it if they want but it's silenced by default?

**Comment by rebeccahum** [comment]
That makes sense, we should leave it for information purposes.
