### ISSUE TITLE
`unserialize()` is not a blocker

### ISSUE THREAD

**Issue by emrikol** [Automattic/VIP-Coding-Standards#17]
Our [documentation](https://vip.wordpress.com/documentation/vip/code-review-what-we-look-for/#serializing-data) lists serialize/unserialize as a blocker.  Should we match it?

**Comment by rebeccahum** [comment]
This is listed as a Warning now: https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/

Closing.
