### ISSUE TITLE
Publish to Packagist?

### ISSUE THREAD

**Issue by nathanielks** [Automattic/VIP-Coding-Standards#173]
Hi there!

Thank you for having a composer.json file present in the repo. Would it also be possible to register the package on Packagist so that it may be accessed that way? Thanks for all your work!

**Comment by GaryJones** [comment]
@nathanielks Not sure when it was added, but it appears to be there now!

https://packagist.org/packages/automattic/vipwpcs

**Comment by nathanielks** [comment]
Thanks for the follow up, @GaryJones!
