### ISSUE TITLE
Flag `plugins_loaded` and possibly all earlier hooks as well

### ISSUE THREAD

**Issue by david-binda** [Automattic/VIP-Coding-Standards#174]
Plugins are loaded on the WordPress.com VIP platform via theme, and the earliest hook to use is thus `after_setup_theme`.

We should flag all earlier hooks in order to prevent issues with plugin initialisation.

**Comment by GaryJones** [comment]
@rebeccahum Seems like another use case for `RestrictedHooks`?

If these hooks should be flagged as an error, then the `hook_args` should contain an `errorlevel` key that states whether each occurrence is reported as an error or a warning.

We'll need a list of all of the earlier hooks.

**Comment by rebeccahum** [comment]
Yep, definitely seems like so.  I wonder if this is is an issue only for VIP Go or not.

**Comment by rebeccahum** [comment]
Thinking back to this...this might flag a lot of false positives when PHPCS is run on plugins though?

**Comment by GaryJones** [comment]
> this might flag a lot of false positives when PHPCS is run on plugins though

According to the OP, I think that's the idea:

> We should flag all earlier hooks in order to prevent issues with plugin initialisation.

**Comment by GaryJones** [comment]
Since we're in the process of moving all VIP clients off of WordPress.com, I'm going to go ahead and close this one, as I don't realistically think it's going to get added and be useful in the next 6 months if it hasn't been added in the last two years.
