### ISSUE TITLE
sanitize_email is a valid sanitization function

### ISSUE THREAD

**Issue by justnorris** [Automattic/VIP-Coding-Standards#182]
phpcs said:
```
ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'sanitize_email'.
```

But `sanitize_email` is a valid sanitization function: https://codex.wordpress.org/Function_Reference/sanitize_email

**Comment by grappler** [comment]
@justnorris Are you sure this is an issue for this repo? You are getting an issue that you are missing an escaping function not a sanitisation function.

**Comment by justnorris** [comment]
Ahh, I see the difference. Thanks, for clearing it up for me @grappler.
