### ISSUE TITLE
WPCS 2.0: Migrate Deprecated VIP Sniffs

### ISSUE THREAD

**Issue by tomjn** [Automattic/VIP-Coding-Standards#187]
WPCS 1.0.0 deprecates VIP sniffs, with the intention that they be removed in a later release. We should copy these sniffs to VIP Minimum appropriatley so that our own sniffs and rules aren't broken by a future release

**Comment by GaryJones** [comment]
All but one of the `WordPressVIPMinimum/Sniffs` implement a core PHPCS sniff (`PHP_CodeSniffer_Sniff` currently, but will be `PHP_CodeSniffer\Sniffs\Sniff` if #190 happens first). There is no dependency on WPCS here.

The other Sniff, `DeclarationCompatibilitySniff`, extends `\PHP_CodeSniffer_Standards_AbstractScopeSniff`. There is no dependency on WPCS here.

----

The `WordPressVIPMinimum` [`ruleset.xml`](https://github.com/Automattic/VIP-Coding-Standards/blob/dae432a40e20ccc4f2122c9b950a6ab510d4ec81/WordPressVIPMinimum/ruleset.xml) includes the following `WordPress.VIP` references:

```xml
	<rule ref="WordPress.VIP">
		<exclude name="WordPress.VIP.ValidatedSanitizedInput.MissingUnslash"/>
		<exclude name="WordPress.VIP.RestrictedFunctions"/>
	</rule>
...
	<rule ref="WordPress.VIP.AdminBarRemoval.DeprecatedSniff">
		<severity>0</severity>
	</rule>
	<rule ref="WordPress.VIP.CronInterval.DeprecatedSniff">
		<severity>0</severity>
	</rule>
	<rule ref="WordPress.VIP.DirectDatabaseQuery.DeprecatedSniff">
		<severity>0</severity>
	</rule>
	<rule ref="WordPress.VIP.FileSystemWritesDisallow.DeprecatedSniff">
		<severity>0</severity>
	</rule>
	<rule ref="WordPress.VIP.OrderByRand.DeprecatedSniff">
		<severity>0</severity>
	</rule>
	<rule ref="WordPress.VIP.PluginMenuSlug.DeprecatedSniff">
		<severity>0</severity>
	</rule>
	<rule ref="WordPressVIPMinimum.VIP.RestrictedFunctions.DeprecatedSniff">
		<severity>0</severity>
	</rule>
	<rule ref="WordPress.VIP.RestrictedVariables.DeprecatedSniff">
		<severity>0</severity>
	</rule>
	<rule ref="WordPress.VIP.SessionFunctionsUsage.DeprecatedSniff">
		<severity>0</severity>
	</rule>
	<rule ref="WordPress.VIP.SessionVariableUsage.DeprecatedSniff">
		<severity>0</severity>
	</rule>
	<rule ref="WordPress.VIP.SlowDBQuery.DeprecatedSniff">
		<severity>0</severity>
	</rule>
	<rule ref="WordPress.VIP.SuperGlobalInputUsage.DeprecatedSniff">
		<severity>0</severity>
	</rule>
	<rule ref="WordPress.VIP.TimezoneChange.DeprecatedSniff">
		<severity>0</severity>
	</rule>
	<rule ref="WordPress.VIP.ValidatedSanitizedInput.DeprecatedSniff">
		<severity>0</severity>
	</rule>
```

----

The `WordPress-VIP-Go` [`ruleset.xml`](https://github.com/Automattic/VIP-Coding-Standards/blob/dae432a40e20ccc4f2122c9b950a6ab510d4ec81/WordPress-VIP-Go/ruleset.xml) includes the following `WordPress.VIP` references:

```xml
	<rule ref="WordPress.VIP.RestrictedFunctions.get_posts">
		<severity>1</severity>
	</rule>	
...
	<rule ref="WordPress.VIP.SuperGlobalInputUsage.AccessDetected">
		<type>warning</type>
	</rule>
```

**Comment by GaryJones** [comment]
> All but one of the WordPressVIPMinimum/Sniffs implement a core PHPCS sniff

Correction - there are three classes in `WordPressVIPMinimum/Sniffs/VIP` that extend WPCS classes directly.

**Comment by GaryJones** [comment]
WPCS has just [removed the VIP sniffs](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/1551) from it's `develop` branch, with the aim to push this out as a WPCS 2.0.0 soon.

As such, we should finish off the migration of the `WordPress.VIP` sniffs, and check and adjust our dependency constraints.
