### ISSUE TITLE
Remove PHPCS 2.X support

### ISSUE THREAD

**Issue by tomjn** [Automattic/VIP-Coding-Standards#190]
WPCS 1.0 is deprecating support for PHPCS 2, which means we won't be able to support PHPCS 2 anyway. We should do the same, and remove the polyfills added to make things work with v2 of PHPCS

**Comment by GaryJones** [comment]
Items seen in passing:

- Remove PHP 5.3 / PHPCS 2.9 references from `.travis.yml`.
- Update implementations of `\PHP_CodeSniffer_Sniff` to be `PHP_CodeSniffer\Sniffs\Sniff`.
- Update single extends of `\PHP_CodeSniffer_Standards_AbstractScopeSniff` to be `PHP_CodeSniffer\Sniffs\AbstractScopeSniff`.
- Update any other PHPCS 2.x classes, per the [alias file](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/WordPress/PHPCSAliases.php). `Tests/` already seem to be using `PHP_CodeSniffer\Tests\Standards\AbstractSniffUnitTest`.
- Remove the [`PHPCSCompatibility.php` file](https://github.com/Automattic/VIP-Coding-Standards/blob/master/WordPressVIPMinimum/PHPCSCompatibility.php), which loaded an aliases file from WPCS.
- Remove the [autoloading](https://github.com/Automattic/VIP-Coding-Standards/blob/dae432a40e20ccc4f2122c9b950a6ab510d4ec81/WordPressVIPMinimum/ruleset.xml#L5) of the `PHPCSCompatibility.php` file.

**Comment by GaryJones** [comment]
> Remove the autoloading of the PHPCSCompatibility.php file.
> Remove the PHPCSCompatibility.php file, which loaded an aliases file from WPCS.

While we [still rely on WPCS classes](https://github.com/Automattic/VIP-Coding-Standards/issues/187#issuecomment-411441746) directly, some aliases need to be maintained, either by referencing the WPCS aliases file, or including an aliases file in VIPCS.
