### ISSUE TITLE
How to flag VIP Coding Standard Warning

### ISSUE THREAD

**Issue by maxhartshorn** [Automattic/VIP-Coding-Standards#194]
As mentioned in the Readme.md, "These ruleset contains only the rules which are considered being "blockers" according to the WordPress.com VIP documentation"

Is there a separate ruleset I need to flag the warnings?

**Comment by rebeccahum** [comment]
@maxhartshorn Thanks for the catch, I've updated the readme.md: https://github.com/Automattic/VIP-Coding-Standards/commit/2b26cbcfcc8feb504aee296bd2bb6ca4d4b7f119
