### ISSUE TITLE
Upcoming changes in WPCS

### ISSUE THREAD

**Issue by jrfnl** [Automattic/VIP-Coding-Standards#21]
Hiya,

We noticed that your repo contains some copies of sniffs from the WPCS which will be affected by upcoming changes in WPCS 0.11.0.

Please read through issue https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/765 to gauge how this will affect your customized sniffs.

As a side-note:
* If your customizations could also be useful for others, please consider pulling them to WPCS.
* If they are about enabling/disabling part of an existing sniff, you could also consider using the `exclude` ruleset directive to disable one or more error message, using the `type` directive in the ruleset to change messages from error to warning or visa versa or sending in a PR to WPCS adding a public property to enable/disable part of the sniff.

For more information about ruleset customizations, please see the [PHPCS wiki](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-ruleset.xml) and please feel invited to respond to the above mentioned WPCS issue or to open an issue if you need help.

**Comment by david-binda** [comment]
Hello @jrfnl ,

> Please read through issue WordPress-Coding-Standards/WordPress-Coding-Standards#765 to gauge how this will affect your customized sniffs.

Will do, thank you very much for reaching out to us!

> if they are about enabling/disabling part of an existing sniff, you could also consider using the exclude ruleset directive to disable one or more error message, using the type directive in the ruleset to change messages from error to warning or visa versa or sending in a PR to WPCS adding a public property to enable/disable part of the sniff.

Thank you for pointing out this approach to customising the messaging. Looks like it will significantly reduce the number of "forked" Sniffs in this repository.

> If your customizations could also be useful for others, please consider pulling them to WPCS.

For sure! Let me, please, first take care of the forks as mentioned above, and then open PRs for the rest of the updates we have done.

**Comment by jrfnl** [comment]
Sounds like a plan! Be aware not all changes have been pulled to WPCS yet, but should be in the near future.

**Comment by jrfnl** [comment]
Oh and you may also find issue https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/614 interesting - the page is expected to be added to the wiki once the PRs related to https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/765 have been merged.

**Comment by jrfnl** [comment]
And and another one you'll probably want to have a look at (all merged already): https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/633

**Comment by jrfnl** [comment]
FYI: the bulk of the changes have now been merged into WPCS `develop`.
