### ISSUE TITLE
Catch usage of `dangerouslySetInnerHTML`

### ISSUE THREAD

**Issue by vaurdan** [Automattic/VIP-Coding-Standards#221]
In React, HTML is escaped by default, but it is possible to output raw HTML using the `dangerouslySetInnerHTML` property and passing in an object with an `__html` key.

Does it makes sense to flag this?

**Comment by nickdaugherty** [comment]
This looks like a dupe of https://github.com/Automattic/VIP-Coding-Standards/issues/145
