### ISSUE TITLE
Detect filter not passed in PHP filter_* functions.

### ISSUE THREAD

**Issue by rinatkhaziev** [Automattic/VIP-Coding-Standards#222]
Any `filter_*` function doesn't do any sanitization unless appropriate filter flags are passed.

That includes `filter_var`, `filter_input`, `filter_var_array`, `fliter_input_array`.

From [the manual](http://php.net/manual/en/function.filter-input.php): 
> filter
The ID of the filter to apply. The Types of filters manual page lists the available filters.
**If omitted, FILTER_DEFAULT will be used, which is equivalent to FILTER_UNSAFE_RAW. This will result in no filtering taking place by default.** 

Effectively, besides actually not doing anything this also leads to an illusion of safety.

At the very least we should detected that the third argument is passed and is not FILTER_DEFAULT or FILTER_UNSAFE_RAW:

http://php.net/manual/en/filter.filters.php

**Comment by rinatkhaziev** [comment]
An example of that would be:
https://github.com/wpcomvip/fb-thrive/blob/495d24e0caf5a87f47738718753075e6ade65c37/plugins/fb-elearning/includes/functions/custom-meta.php#L56

**Comment by rebeccahum** [comment]
Related #115

**Comment by GaryJones** [comment]
@rebeccahum With the function parameters logic from WPCS, it should be relatively trivial to check for this.

See WPCS's [PregQuoteDelimiterSniff](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/81a265a2bee11d2b9a040496792c647aa5c97dca/WordPress/Sniffs/PHP/PregQuoteDelimiterSniff.php) or [StrictInArraySniff](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/81a265a2bee11d2b9a040496792c647aa5c97dca/WordPress/Sniffs/PHP/StrictInArraySniff.php) which check for the presence and value of particular parameter.

**Comment by rebeccahum** [comment]
Closing per #242
