### ISSUE TITLE
WordPressVIPMinimum.VIP.FetchingRemoteData.fileGetContentsUknown buggy error message

### ISSUE THREAD

**Issue by rebeccahum** [Automattic/VIP-Coding-Standards#243]
## Bug Description
Seeing a buggy error message here:

> %s() is uncached. If this is being used to query a remote file please use wpcom_vip_file_get_contents() instead. If it\'s used for a local file please use WP_Filesystem instead. Read more here: **https://vip.wordpress.com/documentation/using-wp_filesystem-instead-of-direct-file-access-functions/** 

stemming from the sniff `WordPressVIPMinimum.VIP.FetchingRemoteData.fileGetContentsUknown` when it detects `file_get_contents()`

## Tested Against `master` branch?

- [x] I have verified the issue still exists in the `master` branch of VIPCS.

**Comment by sboisvert** [comment]
Is the problem the %s? or something else I'm missing?

**Comment by rebeccahum** [comment]
Yes, it should read: 

> file_get_contents is uncached. If this is being used to query a remote file please use wpcom_vip_file_get_contents() instead. If it's used for a local file please use WP_Filesystem instead. Read more here: https://vip.wordpress.com/documentation/using-wp_filesystem-instead-of-direct-file-access-functions/
