### ISSUE TITLE
For internal usage only, flag code altering robots.txt

### ISSUE THREAD

**Issue by david-binda** [Automattic/VIP-Coding-Standards#25]
We usually need to flush the nginx cache for robots.txt when code updates those in order to make the change live.

PHPCS might be the easiest way to surface this extra step we need to take after the deploy.

**Comment by tomjn** [comment]
I'm not so keen on us putting internal use only rules in here, especially if it gets confusing for clients, or if we start taking into account the warnings in metrics, would it not be better to have an internal ruleset dependent on this?
