### ISSUE TITLE
Check correct args in wp_cache_add and wp_cache_set

### ISSUE THREAD

**Issue by david-binda** [Automattic/VIP-Coding-Standards#27]
Some example to catch:

```
wp_cache_add($cache_key,$query,3*HOUR_IN_SECONDS)
wp_cache_add($cache_key,$top_posts,600)
wp_cache_set(self::CACHE_KEY_PODCAST_LOCK,true,'',time()+MINUTE_IN_SECONDS)
```

**Comment by GaryJones** [comment]
What counts as "correct" args here?
What counts as incorrect args?

**Comment by david-binda** [comment]
> What counts as "correct" args here?

Per documentation ( https://developer.wordpress.org/reference/functions/wp_cache_add/ ) it should be following:

`wp_cache_add( int|string $key, mixed $data, string $group = '', int $expire )`

> What counts as incorrect args?

We could start with catching `int` for 3rd param, which is the most common issue, from what I can recall. Passing an `int` meant for `$expire` as a third param, which should be a `string` for `$group`.

Further, it would be cool to catch WordPress default time constant passed as 3rd param (similarly to the `int` case).

And finally, any usage of `time()` function in terms of the 4th param is clearly wrong, but happens time to time. So a heuristic approach simply watching for a pattern which employs `time()` might be enough, imho.

**Comment by GaryJones** [comment]
This seems like it's trying to catch incorrect uses of `wp_cache_add()`.

Would this therefore be better in `WordPress-Extra` in WPCS?

I'm failing to otherwise see what about these checks are specific to VIP.

**Comment by rebeccahum** [comment]
Agreed, I think this would be better in the WPCS, rather than VIPCS.

**Comment by rebeccahum** [comment]
Closing in favour of https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/1512
