### ISSUE TITLE
Consider making AlwaysReturnSniff raise errors instead of warnings

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/VIP-Coding-Standards#293]
## What problem would the enhancement address for VIP?

Incorrect returns from filters can ruin your day :)

## Describe the solution you'd like

Currently `return` problems from WP filters are flagged as Warnings, but I suggest they be raised to Error given their potential impacts and the unlikelihood of _actually_ needing to not return from inside a WP filter.

I guess anywhere that's passing by reference would need to be omitted?

## What code should be reported as a violation?

Any WP filter that doesn't explicitly return a value.

## What could should *not* be reported as a violation?

Filters that _always_ return a value, and (I guess) filters that rely on passing by reference.

**Comment by GaryJones** [comment]
:+1:

For the PR, please also fix the capitalisation (currently `Addwarning` instead of `addWarning`), and switch away from using `sprintf` (https://github.com/Automattic/VIP-Coding-Standards/issues/272).
