### ISSUE TITLE
WPCS 2.0: Remove reference to WPCS' PHPAliases.php

### ISSUE THREAD

**Issue by GaryJones** [Automattic/VIP-Coding-Standards#322]
WPCS has a [ticket](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/1596) to remove the `PHPAliases.php` file that VIPCS currently references.

For WPCS 2.0, we'll need to remove our reference and see what other fixes, if anything, is needed to keep things working.

**Comment by GaryJones** [comment]
That linked PR has now been merged.

As WPCS `2.0.0-RC1` got pushed to `master`, it now means VIPCS `master` is no longer compatible with WPCS `master`.

If using Git, then checkout the WPCS `1.2.1` tag, along with the VIPCS `0.4.0` tag.

If using Composer, then ensure the WPCS constraint is `"^1"` for now.

**Comment by GaryJones** [comment]
Depending on what exactly happens once we remove the reference, we may be able to fix the immediate issues with VIPCS `master` branch not being compatible with WPCS `master` branch, by making the file inclusion conditional on whether it exists or not.

**Comment by GaryJones** [comment]
Interestingly, we've already set the [constraint for WPCS](https://github.com/Automattic/VIP-Coding-Standards/blob/0.4.0/composer.json) to be `1.*` for the VIPCS 0.4.0 release.

If the constraint of `dev-master` is used for WPCS in a project, then VIPCS needs a constraint of `*` to be able to install anything, and that installs 0.2.4, which is the latest version not to have any WPCS constraint.

This 0.2.4 will fail to run though, due to the reference to the missing PHPCSAliases.php file.

Even if this PHPAliases reference could be fixed, WPCS 2.0 still completely removes sniffs from the `WordPress.VIP` category, that VIPCS 0.4.0 and earlier directly reference.

As such, it's only the next release (potentially 0.5.0, or maybe 1.0), where this can be fixed.

**Comment by GaryJones** [comment]
@MattGeri As of right now, WPCS 1.2.1 _is_ the latest release (until tomorrow anyway), so it sounds like your build system has a reference to `master`? And perhaps pulling it down with `git clone`, or as a zip?

Whether it applies to single or multiple projects, not using tags (or letting Composer handle it with constraints), but having a build system rely on `master` may result in conflicts just like you've found.

We're actively working on the next VIPCS release and want to get it released soon.

**Comment by whyisjake** [comment]
> As WPCS 2.0.0-RC1 got pushed to master, it now means VIPCS master is no longer compatible with WPCS master.

> If using Git, then checkout the WPCS 1.2.1 tag, along with the VIPCS 0.4.0 tag.

This should be at the top of the README.

**Comment by GaryJones** [comment]
> This should be at the top of the README.

The very first line after the `Installation` heading is:

> First, make sure you have WPCS 1.* and PHPCS v3+ installed.

The Requirements section also makes it clear that WPCS 1.* is needed.

The composer.json also states the dependencies it works with.

**Comment by imwithsam** [comment]
I ran into this issue running VVV. Currently, it appears to be running WPCS 2.1.0.
