### ISSUE TITLE
Consolidate common methods into base / abstract classes

### ISSUE THREAD

**Issue by GaryJones** [Automattic/VIP-Coding-Standards#359]
We already have one abstract class, but there are other common idioms (like getting tokens from the phpcsFile, and often store them in a class property) and methods (multiple files deal with processing hooks, for example).

We should consider consolidating these into a base `Sniff` class, much like [WPCS does](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/WordPress/Sniff.php), and making our sniff classes extends from this.

**Comment by rebeccahum** [comment]
Would it be viable to just extend from the WPCS Sniff class to utilize the existing methods?

**Comment by GaryJones** [comment]
There's work currently being done by @jrfnl that would put much of the useful utility bits of WPCS into PHPCS itself.

Until our minimum PHPCS level reaches whatever version that gets added in to, we could extend the WPCS `Sniff`, with an eye to refactoring after that (much like WPCS would do anyway).
