### ISSUE TITLE
Improve message for Generic.NamingConventions.ConstructorName.OldStyle

### ISSUE THREAD

**Issue by GaryJones** [Automattic/VIP-Coding-Standards#368]
Out of context, our message is a bit cryptic:

https://github.com/Automattic/VIP-Coding-Standards/blob/7e5b6f666f91f2c03499558b7e36afd27b7dc096/WordPress-VIP-Go/ruleset.xml#L91

What is "This"?

We either need to delete the message, so it defaults to the [message in the sniff](https://github.com/squizlabs/PHP_CodeSniffer/blob/0b44f1c3fc42501af7de2ae8d12426866faef554/src/Standards/Generic/Sniffs/NamingConventions/ConstructorNameSniff.php#L79) or at least incorporate parts of to make the message more useful.

**Comment by tomjn** [comment]
I agree and endorse the suggestion to remove the message and revert to the default sniff message. I suspect it was changed to make it clear this would cause a PHP fatal
