### ISSUE TITLE
Incorrect escaping functions suggested

### ISSUE THREAD

**Issue by emrikol** [Automattic/VIP-Coding-Standards#37]
I just saw this blocker:

`Expected next thing to be an escaping function (like esc_html_ex() or esc_attr_ex()), not '_ex'`

but as far as I can tell, `esc_html_ex()` and `esc_attr_ex()` are not defined ¯\\\_(ツ)\_/¯

**Comment by david-binda** [comment]
This has been addressed in the upstream repository before I was able to look into it 😊 

https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/commit/104857555bfdbb5d45f16a4efad8bf1218eb8951
