### ISSUE TITLE
Re-work WordPressVIPMinimum ruleset test 

### ISSUE THREAD

**Issue by rebeccahum** [Automattic/VIP-Coding-Standards#375]
## What problem would the enhancement address for VIP?
As discussed in #372, we should test for all WordPressVIPMinimum rules in our integration tests where they are being implicitly in the ruleset.  Currently, the tests only account for some rules (e.g. only some in the `RestrictedFunctionsSniff`).

**Comment by rebeccahum** [comment]
We will need to figure out #395 to complete this.

**Comment by GaryJones** [comment]
@rebeccahum Other than the JS tokenizer tests issue, is this otherwise now done?

**Comment by rebeccahum** [comment]
@GaryJones Yep.
