### ISSUE TITLE
Undefined variable: tokens in `WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisSniff.php`

### ISSUE THREAD

**Issue by kjbenk** [Automattic/VIP-Coding-Standards#389]
## Bug Description

When performing a refactor of the sniffs here - https://github.com/Automattic/VIP-Coding-Standards/commit/60283aaa00c7a3d86c0766ddb96df3f8139a87b1 - it appears that one `$tokens` variable was not updated to `$this->tokens` on line 788 - https://github.com/Automattic/VIP-Coding-Standards/commit/60283aaa00c7a3d86c0766ddb96df3f8139a87b1#diff-d92e4180ca5db6d3e817b39bc4eed336R788.

**Comment by GaryJones** [comment]
Good catch - thanks - we'll get that fixed.
