### ISSUE TITLE
Add JS into our ruleset tests

### ISSUE THREAD

**Issue by rebeccahum** [Automattic/VIP-Coding-Standards#395]
Currently, we rely on the `ruleset-test.inc` files for our integration tests which is called from `RulesetTest.php`:

https://github.com/Automattic/VIP-Coding-Standards/blob/0df75ba4c1f7695e88f507fea4f07f422735c7ee/tests/RulesetTest.php#L130-L133

However, I'm not sure what is the best way to go about adding JS tests to it since:
A) closing the PHP tag in the file and adding the offending code for it between script tags doesn't seem to catch the correct tokenizers as it processes it as `T_INLINE_HTML`.  
B) passing `-- extensions=inc/php,inc/js` into the shell also doesn't seem to trigger the sniffs as well.

Do we need to add another test file for our integration tests specifically to catch for our JS sniffs?

**Comment by rebeccahum** [comment]
For posterity, due to this issue, I'm unable to add the following rulesets to our integration tests:

* everything in the JS folder
* Security/Twig

**Comment by GaryJones** [comment]
With an eye on #442, and the trickiness of solving this, I think our time is better spent elsewhere.
