### ISSUE TITLE
Reduce Noise from multiple related rulesets

### ISSUE THREAD

**Issue by mdbitz** [Automattic/VIP-Coding-Standards#401]
## What problem would the enhancement address for VIP?
Currently we have rules that trigger on the same piece of code and should be condensed into a single actionable item. 

<img width="1007" alt="Screen Shot 2019-04-03 at 7 54 00 PM" src="https://user-images.githubusercontent.com/5784663/55520510-a528e480-564a-11e9-923c-606b73460a80.png">

In the above the following 3 all get triggered.
* WordPress.VIP.ValidatedSanitizedInput.InputNotValidated
* WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
* WordPress.VIP.SuperGlobalInputUsage.AccessDetected

## Describe the solution you'd like

We should be able to condense these into a single message with clear action(s).  Sanitization is not the same as validated but having 3 items that in this case would be marked as resolved by manual user is excess noise.

**Comment by GaryJones** [comment]
WPCS 2.1 fixes a ton of false positives in this area, so we need to push to get to be able to use it.

Screenshot does appear to show overlap of at least two sniffs though, and if so, we can silence one.

**Comment by rebeccahum** [comment]
Closing because I'm no longer seeing `WordPress.VIP.SuperGlobalInputUsage.AccessDetected`  being flagged from `develop` and tag `2.0.0`.
