### ISSUE TITLE
Minimize false positives on WordPressVIPMinimum.Files.IncludingFile.IncludingFile

### ISSUE THREAD

**Issue by mdbitz** [Automattic/VIP-Coding-Standards#407]
`require_once \PL\PATH . '/inc/endpoints/especiales-endpoint.php';`

`❗️ Warning: Absolute include path must be used. Use get_template_directory(), get_stylesheet_directory() or plugin_dir_path() (WordPressVIPMinimum.Files.IncludingFile.IncludingFile).`

## What problem would the enhancement address for VIP?
Currently clients include files be defining path variables or constants that get used for the path. This makes the IncludingFile rule very noisy with false postiives.

## Describe the solution you'd like
We should enhance the rule check to account for path variables/constants to reduce false positives.

**Comment by mdbitz** [comment]
another example.

`<?php include Wrapper\template_path(); ?>`

**Comment by GaryJones** [comment]
The variable or constants could be defined in another file, so adding code to check for existence in the current file, and then what value it has, will only reduce noise for a small percentage of cases.

In my experience, a variable or constant would typically be defined in the root of the plugin but is used in a different file in the plugin.

**Comment by rebeccahum** [comment]
Constants with `PATH` or `DIR` should be not flagged after discussion with @jrfnl.

**Comment by jrfnl** [comment]
Closing as the principle premise of this issue has been addressed in #638. Further improvements for this sniff are needed, but will be addressed as part of #514.
