### ISSUE TITLE
Ensure that dangerouslySetInnerHTML rule recognizes common sanitization practices/libraries.

### ISSUE THREAD

**Issue by mdbitz** [Automattic/VIP-Coding-Standards#409]
` <div className='Results__mediaText' dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(item.title.rendered) }} />`

`🚫 Error: Any HTML passed to dangerouslySetInnerHTML gets executed. Please make sure it's properly escaped (WordPressVIPMinimum.JS.DangerouslySetInnerHTML.dangerouslySetInnerHTML).`

## Describe the solution you'd like

The above code triggered the dangerouslySetInnerHTML ruleset. However it utilizes DomPurify to properly sanitize and escape the content. The rule should be able to recognize this.

**Comment by rebeccahum** [comment]
Closing in favour of #267.
