### ISSUE TITLE
PHPStorm, phpcs: ERROR: Referenced sniff "WordPress.Security.EscapeOutput" does not exist

### ISSUE THREAD

**Issue by Mahjouba91** [Automattic/VIP-Coding-Standards#414]
## Bug Description

Hello,

I am trying to use the WordPress VIP coding standards in my PHPStorm code sniffer.

I have tested both local installation and global one using composer, and I have always the same error on PHPStorm which is triggered.

Otherwise, other WPCS sniffers work well.

And even, when I'm testing the VIPCS through the command line, it works well.

```
xxx-MacBook-Pro:~ xxx$ phpcs --standard=WordPress-VIP-Go -sp --basepath=. --ignore=vendor /Users/xxx/PhpstormProjects/yyy/themes/yyy/functions.php
E 1 / 1 (100%)



FILE: PhpstormProjects/yyy/themes/yyy/functions.php
--------------------------------------------------------------------------------------------------------------------------------
FOUND 11 ERRORS AND 13 WARNINGS AFFECTING 17 LINES
--------------------------------------------------------------------------------------------------------------------------------
 228 | ERROR   | Detected usage of a non-sanitized, non-validated input variable $_SERVER:
     |         | "{$_SERVER['HTTP_HOST']}{$_SERVER['REQUEST_URI']}"
     |         | (WordPress.Security.ValidatedSanitizedInput.InputNotValidatedNotSanitized)
 228 | ERROR   | Detected usage of a non-sanitized, non-validated input variable $_SERVER:
     |         | "{$_SERVER['HTTP_HOST']}{$_SERVER['REQUEST_URI']}"
     |         | (WordPress.Security.ValidatedSanitizedInput.InputNotValidatedNotSanitized)
 235 | WARNING | Detected usage of a non-sanitized input variable: $_SERVER
     |         | (WordPress.Security.ValidatedSanitizedInput.InputNotSanitized)
 235 | ERROR   | Detected usage of a non-validated input variable: $_SERVER
     |         | (WordPress.Security.ValidatedSanitizedInput.InputNotValidated)
 308 | WARNING | Processing form data without nonce verification.
     |         | (WordPress.Security.NonceVerification.NoNonceVerification)
 308 | WARNING | Processing form data without nonce verification.
     |         | (WordPress.Security.NonceVerification.NoNonceVerification)
 309 | WARNING | Processing form data without nonce verification.
     |         | (WordPress.Security.NonceVerification.NoNonceVerification)
 309 | WARNING | Detected usage of a non-sanitized input variable: $_GET
     |         | (WordPress.Security.ValidatedSanitizedInput.InputNotSanitized)
 310 | WARNING | Processing form data without nonce verification.
     |         | (WordPress.Security.NonceVerification.NoNonceVerification)
 339 | WARNING | This comment is 44% valid code; is this commented out code? (Squiz.PHP.CommentedOutCode.Found)
 558 | WARNING | Processing form data without nonce verification.
     |         | (WordPress.Security.NonceVerification.NoNonceVerification)
 558 | WARNING | Processing form data without nonce verification.
     |         | (WordPress.Security.NonceVerification.NoNonceVerification)
 558 | WARNING | Processing form data without nonce verification.
     |         | (WordPress.Security.NonceVerification.NoNonceVerification)
 596 | WARNING | parse_url() is discouraged because of inconsistency in the output across PHP versions; use wp_parse_url()
     |         | instead. (WordPress.WP.AlternativeFunctions.parse_url_parse_url)
 786 | ERROR   | All output should be run through an escaping function (see the Security sections in the WordPress Developer
     |         | Handbooks), found '$html'. (WordPress.Security.EscapeOutput.OutputNotEscaped)
 971 | WARNING | Detected usage of a non-sanitized input variable: $_SERVER
     |         | (WordPress.Security.ValidatedSanitizedInput.InputNotSanitized)
 971 | ERROR   | Detected usage of a non-validated input variable: $_SERVER
     |         | (WordPress.Security.ValidatedSanitizedInput.InputNotValidated)
 983 | WARNING | var_dump() found. Debug code should not normally be used in production.
     |         | (WordPress.PHP.DevelopmentFunctions.error_log_var_dump)
 986 | ERROR   | error_log() found. Debug code should not normally be used in production.
     |         | (WordPress.PHP.DevelopmentFunctions.error_log_error_log)
--------------------------------------------------------------------------------------------------------------------------------

Time: 555ms; Memory: 18MB
```

## Error Code

```
15:19	PHP Code Sniffer
			phpcs: ERROR: Referenced sniff "WordPress.Security.EscapeOutput" does not exist
			Run "phpcs --help" for usage information
```

## Environment

| Question                | Answer
| ------------------------| -------
| PHP version             | 7.1.23
| PHP_CodeSniffer version | 3.4.2
| WPCS version           | 1.2.1
| VIPCS version           | 1.0.0

## Tested Against `master` branch?

- [x] I have verified the issue still exists in the `master` branch of VIPCS.

**Comment by GaryJones** [comment]
Double check which version of WPCS you're actually using with PhpStorm. If it's working on the command line, it's likely to be a PhpStorm configuration issue - specifically, check which version of `phpcs` you're pointing it to.

**Comment by Mahjouba91** [comment]
I think you're right, there were something wrong with my configuration, I tried all things and it seems to work well now, thank you!

**Comment by Mahjouba91** [comment]
Hey, I'm sorry, but have to reopen this issue.

Instead of using code sniffer with composer global, now I want to use it only in my current PHPStorm project managed by composer.

So I have installed dependencies, configure the good path for code sniffer in Quality tool menu `/vendor/squizlabs/php_codesniffer/bin/phpcs`

Did the same for PHP Code Sniffer validation in Editor > Inspection with this path: `vendor/automattic/vipwpcs`, selected WordPress-VIP-Go, and I still have this issue mentioned on the ticket description.

Otherwise, when using Wordpress-Extra coding standard, it works like a charm. So there is something not stable with the VIP CS I think.

Also, when it was working globally, I did not have the WordPress coding standards, only VIP ones, is it normal ? It should be inherited, no?

**Comment by Mahjouba91** [comment]
@GaryJones Could you please reopen the issue ?

**Comment by GaryJones** [comment]
> Instead of using code sniffer with composer global, now I want to use it only in my current PHPStorm project managed by composer.

Ensure you have the https://packagist.org/packages/dealerdirect/phpcodesniffer-composer-installer package in your project's `require-dev`, alongside `automattic/vipwpcs`. This will handle the registration for you.

> So I have installed dependencies, configure the good path for code sniffer in Quality tool menu /vendor/squizlabs/php_codesniffer/bin/phpcs

This can be `vendor/bin/phpcs`.

Because the path to the standards will now be auto-registered when you run `composer install` or `composer update`, then you can refresh the Inspection setting and set it to `WordPress-VIP-Go` from the dropdown.

Better, create a `.phpcs.xml.dist` file for the project (see [this](https://github.com/GaryJones/plugin-boilerplate/blob/master/.phpcs.xml.dist) as a starting point) and then add in which standards and configurations you want - maybe `WordPress-Extra` AND `WordPress-VIP-Go`, AND `WordPress-Docs`, AND PHPCompatibilityWP, etc.

**Comment by Mahjouba91** [comment]
Very good feedback, thank you very much for your help, everything works like a charm now

**Comment by Mahjouba91** [comment]
Tried to configure the .phpcs.xml thing, but it did not worked well for me (Do you have a tutorial ?). Then tried to come back to my previous configuration, and it doesn't work anymore.

I have the same error again:

phpcs: ERROR: Referenced sniff "WordPress.Security.EscapeOutput" does not exist

My actual configuration for composer dev dependencies look like this: 
```
    "require-dev": {
        "phpunit/phpunit": "6.5.9",
        "wp-phpunit/wp-phpunit": "^5.0",
        "automattic/vipwpcs": "^1.0",
        "wp-coding-standards/wpcs": "^1.0",
        "phpcompatibility/phpcompatibility-wp": "^2.0",
        "dealerdirect/phpcodesniffer-composer-installer": "^0.5.0"
    },
```

The Code sniffer local configuration is set to `/vendor/bin/phpcs`

And the PHP Code Sniffer validation is set to WordPress-VIP-Go, so I do not understand how it works.

Do you have any idea ? @GaryJones

**Comment by GaryJones** [comment]
The devDependecies look correct, but that doesn't necessarily say what's installed. Can you share what `composer show -D` says?

**Comment by Mahjouba91** [comment]
Hello @GaryJones,

I still have the issue unfortunately. Same config than above.

When I set the coding standard to WordPress-Extra it works well as expected, but when I try with WordPress-VIP-Go, it doesn't work at all (same error code than issue title).

Here the composer show -D result: 

```
automattic/vipwpcs                             2.0.0              PHP_CodeSniffer rules (sniffs) to enforce WordPress VIP minimum coding conventions
composer/installers                            v1.6.0             A multi-framework Composer library installer
dealerdirect/phpcodesniffer-composer-installer v0.5.0             PHP_CodeSniffer Standards Composer Installer Plugin
oscarotero/env                                 v1.2.0             Simple library to consume environment variables
phpcompatibility/phpcompatibility-wp           2.0.0              A ruleset for PHP_CodeSniffer to check for PHP cross-version compatibility issues in projects, while accounting for polyfills provided by WordPress.
phpunit/phpunit                                6.5.14             The PHP Unit Testing framework.
roave/security-advisories                      dev-master ea693fa Prevents installation of composer packages with known security vulnerabilities: no API, simply require it
roots/wordpress                                5.2.2              WordPress is web software you can use to create a beautiful website or blog.
roots/wp-config                                1.0.0              Collect configuration values and safely define() them
roots/wp-password-bcrypt                       1.0.0              WordPress plugin which replaces wp_hash_password and wp_check_password's phpass hasher with PHP 5.5's password_hash and password_verify using bcrypt.
squizlabs/php_codesniffer                      3.4.2              PHP_CodeSniffer tokenizes PHP, JavaScript and CSS files and detects violations of a defined set of coding standards.
vlucas/phpdotenv                               v3.4.0             Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagically.
wp-coding-standards/wpcs                       2.1.1              PHP_CodeSniffer rules (sniffs) to enforce WordPress coding conventions
wp-phpunit/wp-phpunit                          5.2.2              WordPress core PHPUnit library
```

**Comment by GaryJones** [comment]
I assume you've updated your `require-dev` slightly, as that collection of installed packages wouldn't quite match the `require-dev` you posted before.

Can you please share screenshots of PHPStorm UI showing the Composer configuration, the PHPCS configuration, the Editor -> Inspection screen, and also the command line showing full paths with `phpcs -I`.

**Comment by dingo-d** [comment]
@Mahjouba91 Try to remove the `Installed standard paths` in the Preferences->Editor->Inspections->Quality tools->PHP Code Sniffer validation and use dealerdirect to resolve the paths.

This worked for me (on MacOS)
