### ISSUE TITLE
Missing escaping is not caught in PHP short tags

### ISSUE THREAD

**Issue by emrikol** [Automattic/VIP-Coding-Standards#43]
Example: `<section id="live-map" class="masthead live-map" data-detect="<?= $location; ?>"`

Also, we should just block short tags :)

**Comment by david-binda** [comment]
@emrikol I have addressed the shorthand echo in #44 , but we still, imho, should report on missing escaping, if it's missing. Let me reopen this.

**Comment by david-binda** [comment]
@emrikol I have opened an issue in the upstream - https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/857

We'll have to sync with develop (and master in case develop gets merged soon) anyway. So I'm going to close this issue in favour of the upstream one.
