### ISSUE TITLE
Propably missing a warning on prepend method

### ISSUE THREAD

**Issue by manooweb** [Automattic/VIP-Coding-Standards#435]
as html , append here 

https://github.com/Automattic/VIP-Coding-Standards/blob/8544a94c32f990b6669f2c7f034d4ba75ccbb558/WordPressVIPMinimum/Sniffs/JS/HTMLExecutingFunctionsSniff.php#L27-L33

I have no warning when I ran WPCS VIP Minimum

**Comment by GaryJones** [comment]
Thanks for reporting!
