### ISSUE TITLE
Publish a new release?

### ISSUE THREAD

**Issue by jenkoian** [Automattic/VIP-Coding-Standards#457]
Having upgraded to latest WP core standards now getting a load of warnings `The "WordPress.WP.TimezoneChange" sniff has been deprecated.` which have been addressed and merged in master (https://github.com/Automattic/VIP-Coding-Standards/commit/d8fbf909bff6991db130add04649a80303c4b654). 

Any chance of a new release so we can easily update to a stable tag?

**Comment by GaryJones** [comment]
Thanks for the reminder!

Yes, we need to check what else can go in a patch release and make the update, hopefully in the next few days. cc @rebeccahum

**Comment by alecgeatches** [comment]
Seeing the same thing here. My current CI workaround is to add

```
--exclude=WordPress.WP.TimezoneChange
``` 

to my `phpcs` command-line options.

**Comment by paulschreiber** [comment]
This was fixed in December. Ugh. Please publish a release.

**Comment by GaryJones** [comment]
It's coming next week!

**Comment by GaryJones** [comment]
https://github.com/Automattic/VIP-Coding-Standards/releases/tag/2.1.0
