### ISSUE TITLE
Why is VIP excluding whitespace checks

### ISSUE THREAD

**Issue by msaggiorato** [Automattic/VIP-Coding-Standards#460]
Why is VIP excluding these checks for whitespace related rules, which are included in WP Core and WP Extra coding standards?

https://github.com/Automattic/VIP-Coding-Standards/blob/89d7b350181cf9537775a5682bcbaeef5425e4b8/WordPressVIPMinimum/ruleset.xml#L49-L56

I'm not proposing a change, but just noticing that there's inconsistencies here, and i'm interested in knowing the reasoning behind this.

Thanks.

**Comment by GaryJones** [comment]
Hi @msaggiorato,

The focus for code review on VIP is security, performance, and platform capability. Where you have your braces and line wraps isn't a concern.

Obviously, we'd encourage clients to follow the _code style_ rules from WPCS (they can be combined with VIPCS), as it then makes code easier to read and consistent to write, but it's not a blocker for VIP approval :-)

**Comment by msaggiorato** [comment]
Hey @GaryJones!

Great, I understand now the point of excluding this.

Wouldn't it be better to maybe lower the priority of the rules instead of excluding it? 

I see you do that in some other sections of the standards:

https://github.com/Automattic/VIP-Coding-Standards/blob/develop/WordPress-VIP-Go/ruleset.xml#L305-L310

Not sure if you would be able to run `phpcs --severity=0` to include these silenced rules on the report.

I'm considering using a `phpcs.xml` file to check for WordPress-Extra and VIP standards, and with the current implementation, there's no way to run phpcbf to fix these whitespace issues without running 2 separate standards checks. Also using the `phpcs.xml` file makes it possible for the editor to pick up 2 standards right away, on a project by project basis without the need for the developer to set up the environment (similar to how `.eslintrc` or other similar files would work).

I may be missing something here, so please let me know what you think.

Thanks!

**Comment by GaryJones** [comment]
I'm not keen on our standards overriding the severity of sniffs from others. In the case you've highlighted, we're overriding one of our checks, along with one from Generic standard, but both are set in the WordPressVIPMinimum ruleset, which the WordPress-VIP-Go ruleset inherits from.

> Not sure if you would be able to run phpcs --severity=0 to include these silenced rules on the report.

Try it and see :-) I think the minimum is --severity=1, since severity 0 is the same as exclusion.
