### ISSUE TITLE
False positive for require_once .phar - cannot be loaded via file_get_contents

### ISSUE THREAD

**Issue by kkmuffme** [Automattic/VIP-Coding-Standards#478]
`require_once( 'some.phar' );`

will trigger:
WordPressVIPMinimum.Files.IncludingNonPHPFile.IncludingNonPHPFile

.phar files however must be loaded via include/require, as otherwise they won't work.
Please adjust the sniff.

**Comment by GaryJones** [comment]
What's the use case for needing to include a `.phar` file?

**Comment by kkmuffme** [comment]
various libraries, e.g. some of composer, come as .phar (or some are even only available as phar, but in general it's most often easier to use the phar if its available)
e.g. maxmind geoip, AWS PHP SDK,...

e.g use cases for AWS SDK is translation, SMS, email, customer service,...

**Comment by GaryJones** [comment]
These are typically development tools to be run locally, and usually available to be installed via Composer - as such, they wouldn't need to be pushed up to a repo. As such, you could ignore them, either at your PHPCS config file level, or with a PHPCS ignore line at the point of inclusion.

I haven't seen requests for this before to make me consider making a change to the sniff itself.

**Comment by kkmuffme** [comment]
All things mentioned in my previous comment are NOT development tools and must be pushed in the plugin/repo despite being installed with composer.

If I provide a pull request that includes .phar will it be merged?

**Comment by jrfnl** [comment]
I agree with @kkmuffme on this. A fix for this is included in PR #586.
