### ISSUE TITLE
Update output when dbDelta is found in the codebase

### ISSUE THREAD

**Issue by BrookeDot** [Automattic/VIP-Coding-Standards#479]
## What problem would the enhancement address for VIP?
When a codebase is scanned and `dbDelta` is found the following error is output:

> All database modifications have to approved by the WordPress.com VIP team.

https://github.com/Automattic/VIP-Coding-Standards/blob/master/WordPressVIPMinimum/Sniffs/Functions/RestrictedFunctionsSniff.php#L94

While this was previously true on WordPress.com we no longer require the VIP team to approve all database changes at every code review level. 

## Describe the solution you'd like

As this can still cause performance problems, we should continue to flag this as a possible issue. However, instead of stating that the VIP team needs to approve the change, we could link to documentation of some things to check or other helpful tips.

**Comment by GaryJones** [comment]
@BrookeDot Did you fancy doing a PR that changes this (in the the `WordPress-VIP-Go` ruleset) from Error to Warning, and adjusts the message wording?

**Comment by BrookeDot** [comment]
Happy to submit a PR for the text change, but before I do I think we need to have a few more internal discussions around what the expectations should be for dbDelta on VIP Go.

**Comment by rebeccahum** [comment]
After some internal discussion, it might be good to rid this warning because the usefulness of it is marginal on VIP Go.

**Comment by BrookeDot** [comment]
Opened a PR ( #692) to remove the rule.
