### ISSUE TITLE
Remove BatCache related sniff

### ISSUE THREAD

**Issue by GaryJones** [Automattic/VIP-Coding-Standards#492]
## What problem would the enhancement address for VIP?

~Words matter, and the current understanding is that _whitelist_ has negative connotations for some people that can be easily avoided by using a different term.~

BatCache is not used on the current VIP platform, so this sniff is no longer needed.

## Describe the solution you'd like

~Change class, class properties and any other references to _whitelist_ for something else.~

Remove the sniff.

## Additional context

~Apart from the changelog, the only other references seem to be in relation to the BatcacheWhitelistedParams sniff and related test files.~

**Comment by rebeccahum** [comment]
+1000000

**Comment by GaryJones** [comment]
This _is_ important, but changing the class name will create a backwards compatibility break, so that means it needs to be done on a major release.

It's possible that all of the VIP clients will have moved over from WordPress.com VIP to VIP Go platform by the time the VIPCS is released, which means that this issue can change to removing this sniff completely, since it's only used in the WordPress-VIP-Minimum ruleset.

**Comment by GaryJones** [comment]
> It's possible that all of the VIP clients will have moved over from WordPress.com VIP to VIP Go platform by the time the VIPCS is released, which means that this issue can change to removing this sniff completely, since it's only used in the WordPress-VIP-Minimum ruleset.

This is now correct, so the BatCache-related sniff can be removed completely now.

**Comment by GaryJones** [comment]
Closing in favour of #613.
