### ISSUE TITLE
WPCS 3.0 removes WordPress.PHP.StrictComparisons

### ISSUE THREAD

**Issue by GaryJones** [Automattic/VIP-Coding-Standards#493]
WPCS 3.0 [removes](https://github.com/WordPress/WordPress-Coding-Standards/pull/1919) the `WordPress.PHP.StrictComparisons` sniff.

Without any changes, this will cause errors, so we should pull in `Universal.Operators.StrictComparisons` as well, once we have PHPCSExtra as a dependency.

**Comment by jrfnl** [comment]
Closing as duplicate of #603, which was fixed in #779
