### ISSUE TITLE
var_export should be treated like var_dump

### ISSUE THREAD

**Issue by emrikol** [Automattic/VIP-Coding-Standards#53]
Currently `var_dump` is flagged, but `var_export` which has similar functionality is not.  I believe we should flag it as well.

**Comment by emrikol** [comment]
Oh, I do see that it gets marked as a warning.  Is that enough, or should it be a blocker?

**Comment by david-binda** [comment]
Thank you for pointing this out. the `var_dump` handling is a big mess right now and is actually an error by mistake.

But for our use case of the PHPCS, it really should be an error.

**Comment by rebeccahum** [comment]
Closing per #232
