### ISSUE TITLE
Flag str_replace with all three params being static

### ISSUE THREAD

**Issue by david-binda** [Automattic/VIP-Coding-Standards#55]
eg: `'action'   => str_replace( 'fusion-', '', 'single' ),`

VaultPress is complaining about it as well and we should prevent VP from sending warnings on code we review.

**Comment by nickdaugherty** [comment]
What specifically does VP complain about? The function itself doesn't throw PHP warnings when called with non-variable inputs, so I'm curious what the concern here is (besides the code not being particularly useful).

**Comment by david-binda** [comment]
Such a call is totally valid from the execution point of view. Just usually useless, unless it's used to obfuscate it's meaning or make the code less readable.

When I said "warnings", I did not mean PHP warning, but rather a prompt for a need of manual review of the bit of the code. We should reflect that in the sniff - eg.: by not producing an error, but rather a warning.

**Comment by nickdaugherty** [comment]
Sounds good, thanks for the extra info.
