### ISSUE TITLE
Review minimum-stability

### ISSUE THREAD

**Issue by GaryJones** [Automattic/VIP-Coding-Standards#562]
The `minimum-stability` value in the `composer.json` file is `RC`.

We should review if that's still needed, and if not, move it to `stable`.

May wait to see when exactly it makes sense to add PHPCSUtils as a `require` dependency i.e. 1.0.0-RC.

**Comment by jrfnl** [comment]
IMO: leave it alone, it's not that relevant. It only applies to this project anyway, not to projects `require`-ing this project. (It's a root-only setting)

https://getcomposer.org/doc/04-schema.md#minimum-stability
