### ISSUE TITLE
Check for RestrictedVariables wrong

### ISSUE THREAD

**Issue by kkmuffme** [Automattic/VIP-Coding-Standards#568]
e.g. WordPressVIPMinimum.Variables.RestrictedVariables.session___SESSION
will trigger for code like:

```
// dont cache it if we have an active PHP session
if ( isset( $_SESSION ) ) {
	$cache = false;
}
```

which doesn't make sense, as it's not even being used.
Afaik WP PHPCS had the same issue, but they fixed it already quite some time ago

**Comment by GaryJones** [comment]
Hi @kkmuffme. We've added a fix in the `develop` branch. Please check it out and see if your code has stopped reporting for what you reported. Thanks!
