### ISSUE TITLE
Remove reference WordPress.Security.NonceVerification.NoNonceVerification

### ISSUE THREAD

**Issue by rebeccahum** [Automattic/VIP-Coding-Standards#605]
Per the changelog of WPCS 2.0.0-RC1:

> The WordPress.Security.NonceVerification sniff used the same error code for both an error as well as a warning. The old error code NoNonceVerification is no longer used. The error now uses the Missing error code, while the warning now uses the Recommended error code. If you are referencing the old error code in a ruleset XML file or in inline annotations, please update these to use the new codes instead.

I think we can remove the reference from the WordPress-VIP-Go ruleset: https://github.com/Automattic/VIP-Coding-Standards/blob/60ad148168258afccd05ff0429d53a7e810270a5/WordPress-VIP-Go/ruleset.xml#L132

The sniff is still inherited from the parent WordPressVIPMinimum (albeit, different error codes now):

https://github.com/Automattic/VIP-Coding-Standards/blob/60ad148168258afccd05ff0429d53a7e810270a5/WordPressVIPMinimum/ruleset.xml#L21

**Comment by GaryJones** [comment]
Was the `NoNonceVerification` error code completely removed in WPCS 2.0.0?

**Comment by rebeccahum** [comment]
Appears to be: https://github.com/WordPress/WordPress-Coding-Standards/blob/2.0.0/WordPress/Sniffs/Security/NonceVerificationSniff.php

**Comment by jrfnl** [comment]
Just for reference - this is the PR/commit which changed the error codes and also explains _why_ the change was made: https://github.com/WordPress/WordPress-Coding-Standards/pull/1487
