### ISSUE TITLE
Update WordPress.WP.GlobalVariablesOverride.OverrideProhibited to WordPress.WP.GlobalVariablesOverride.Prohibited in WordPress-VIP-Go

### ISSUE THREAD

**Issue by rebeccahum** [Automattic/VIP-Coding-Standards#609]
As of WPCS 2.0.0-RC1:

> The WordPress.WP.GlobalVariablesOverride.OverrideProhibited error code has been replaced by the WordPress.WP.GlobalVariablesOverride.Prohibited error code. If you are referencing the old error code in a ruleset XML file or in inline annotations, you may need to update it.

We'll need to update it in `WordPress-VIP-Go`: https://github.com/Automattic/VIP-Coding-Standards/blob/60ad148168258afccd05ff0429d53a7e810270a5/WordPress-VIP-Go/ruleset.xml#L226

**Comment by jrfnl** [comment]
> I'd recommend for this severity change to be removed completely.

See: https://github.com/Automattic/VIP-Coding-Standards/pull/610#issuecomment-790186115
