### ISSUE TITLE
Remove ZoninatorSniff

### ISSUE THREAD

**Issue by rebeccahum** [Automattic/VIP-Coding-Standards#612]
Since all sites have moved from .com, we can remove the sniff since REST API is loaded by default.

>  * This sniff reminds the developers to check whether the WordPress Core REST API is enabled
> * along with loading v0.8 and above.

https://github.com/Automattic/VIP-Coding-Standards/blob/60ad148168258afccd05ff0429d53a7e810270a5/WordPressVIPMinimum/Sniffs/Compatibility/ZoninatorSniff.php#L75

Not to mention that the function mentioned in the error message is deprecated:

https://github.com/Automattic/vip-go-wpcom-compat/blob/79bce981b331c7ed9e608f06b2407f976dac9235/wpcom-deprecated-functions.php#L9

**Comment by jrfnl** [comment]
Action plan suggestion:
1. Deprecate the sniff in the next release (2.x) by:
    1. Adding a deprecation warning to the sniff which will inform people to remove the sniff reference from their own custom ruleset.
    2. Silencing all messages from the sniff from within the `VIPMinimum` ruleset, effectively removing the sniff already for people using the standard rulesets.
2. Remove the actual sniff in the next major, i.e. 3.0.0.
