### ISSUE TITLE
Remove site_option related sniffs/groupings

### ISSUE THREAD

**Issue by rebeccahum** [Automattic/VIP-Coding-Standards#615]
Since VIP Go allows multisites, there's no reason to flag for the usage:

https://github.com/Automattic/VIP-Coding-Standards/blob/6d3f5267bee6f0e7548aacc3881b2ac0bcd981e9/WordPressVIPMinimum/Sniffs/Functions/RestrictedFunctionsSniff.php#L262-L270

It's silenced anyways on WordPress-VIP-Go:

https://github.com/Automattic/VIP-Coding-Standards/blob/6d3f5267bee6f0e7548aacc3881b2ac0bcd981e9/WordPress-VIP-Go/ruleset.xml#L296-L304

**Comment by jrfnl** [comment]
Same as for #614:

> Loosely related to #600.
> 
> The difference between #600 and these changes, is that these are **_not_** breaking changes as no _sniffs_ are removed, only error codes (and groups).
> 
> This means that this change might make some inline ignore annotations _redundant_ and possibly make some values in custom properties in rulesets redundant, but other than that, it will not _break_ rulesets and it will not _break_ runs.
> 
> In other words, these changes are "allowed" to go into a next minor and don't _need_ to wait for the next major (though a choice can be made to let this wait for the next major anyway).

**Comment by jrfnl** [comment]
Open question - there are more multisite related restricted functions, should those be allowed now as well ?

https://github.com/Automattic/VIP-Coding-Standards/blob/6d3f5267bee6f0e7548aacc3881b2ac0bcd981e9/WordPressVIPMinimum/Sniffs/Functions/RestrictedFunctionsSniff.php#L53-L59

https://github.com/Automattic/VIP-Coding-Standards/blob/6d3f5267bee6f0e7548aacc3881b2ac0bcd981e9/WordPressVIPMinimum/Sniffs/Functions/RestrictedFunctionsSniff.php#L99-L107

**Comment by jrfnl** [comment]
Just saw #616 which answers the first part of the question (removing `get_super_admins` restiction).

**Comment by rebeccahum** [comment]
For the `switch_to_blog`, we have a custom error message for it at:
https://github.com/Automattic/VIP-Coding-Standards/blob/1fa0266752aed5f53b369e3e60858f03d9ff9aac/WordPress-VIP-Go/ruleset.xml#L249

I think we can change the type to warning and the message directly on the sniff?
