### ISSUE TITLE
Remove get_super_admin grouping from RestrictedFunctions

### ISSUE THREAD

**Issue by rebeccahum** [Automattic/VIP-Coding-Standards#616]
No need to flag for super admin on VIP Go:

https://github.com/Automattic/VIP-Coding-Standards/blob/6d3f5267bee6f0e7548aacc3881b2ac0bcd981e9/WordPressVIPMinimum/Sniffs/Functions/RestrictedFunctionsSniff.php#L53-L59

Silenced here anyways:

https://github.com/Automattic/VIP-Coding-Standards/blob/6d3f5267bee6f0e7548aacc3881b2ac0bcd981e9/WordPress-VIP-Go/ruleset.xml#L305-L307

**Comment by jrfnl** [comment]
Same as for #614:

> Loosely related to #600.
> 
> The difference between #600 and these changes, is that these are **_not_** breaking changes as no _sniffs_ are removed, only error codes (and groups).
> 
> This means that this change might make some inline ignore annotations _redundant_ and possibly make some values in custom properties in rulesets redundant, but other than that, it will not _break_ rulesets and it will not _break_ runs.
> 
> In other words, these changes are "allowed" to go into a next minor and don't _need_ to wait for the next major (though a choice can be made to let this wait for the next major anyway).
