### ISSUE TITLE
switch_to_blog: Change message to reflect WordPress-VIP-Go ruleset and downgrade to "Warning"

### ISSUE THREAD

**Issue by rebeccahum** [Automattic/VIP-Coding-Standards#643]
This is a two-part issue since I _think_ step #2 will need to be done in 3.x due to it being a breaking change (can you please confirm @jrfnl?)

**Step 1**
Mentioned in #615, we should change the message in the `WordPressVIPMinimum.Functions.RestrictedFunctions.switch_to_blog_switch_to_blog` error code to reflect the one being changed in WordPress-VIP-Go since the current one is outdated.

From:

https://github.com/Automattic/VIP-Coding-Standards/blob/6d3f5267bee6f0e7548aacc3881b2ac0bcd981e9/WordPressVIPMinimum/Sniffs/Functions/RestrictedFunctionsSniff.php#L103

To: https://github.com/Automattic/VIP-Coding-Standards/blob/1fa0266752aed5f53b369e3e60858f03d9ff9aac/WordPress-VIP-Go/ruleset.xml#L249

**Step 2**
Downgrade to warning type at sniff level and remove modification in `WordPress-VIP-Go` ruleset:

https://github.com/Automattic/VIP-Coding-Standards/blob/1fa0266752aed5f53b369e3e60858f03d9ff9aac/WordPress-VIP-Go/ruleset.xml#L247

**Comment by jrfnl** [comment]
@rebeccahum Neither of these changes is a breaking change as custom rulesets and ignore annotations don't filter on error/warning, just on sniff name or error code.

In other words, if you'd like to adjust PR #649, that should be fine to go into `2.3.0` still.

**Comment by GaryJones** [comment]
If something bumped up from a warning to an error, then we may want to consider that to be a breaking change, as it could break builds.

**Comment by jrfnl** [comment]
@GaryJones Good point and I agree that's very true from a functional point of view.

In this particular case, however, we're talking _bumping down_ to a `warning`.

On top of that, the bumping down would only affect people who selectively include sniffs or use the `WordPressVIPMinimum ruleset. The `WordPress-VIP-Go` ruleset users are not affected as the rule in question was already a `warning` for them.
