### ISSUE TITLE
Question: how to correctly escape query parameters when used in inline js?

### ISSUE THREAD

**Issue by kkmuffme** [Automattic/VIP-Coding-Standards#679]
I have this code (used for a Google JS SDK/API) used in an inline script tag, since the recaptcha API key is stored in WP db, but I dont know how to correctly escape it with the new rules (since I'm getting WordPressVIPMinimum.Security.ProperEscapingFunction.hrefSrcEscUrl but esc_url cannot be used for this, since it will put a https://)

```php
xhr.send( '/some/url?some-arg=' + jsVariableFromGoogleAPI + '&api-key=<?php echo esc_attr( rawurlencode( $api_key ) ); ?>' );
```

**Comment by jrfnl** [comment]
I cannot seem to reproduce the issue. Tested this code snippet with VIPCS 2.3.0, 2.3.1, but neither seem to give any error for this line.

**Comment by kkmuffme** [comment]
Hm, strange suddenly I dont get that error anymore either.
