### ISSUE TITLE
Cannot declare class VariableAnalyses... when using standards

### ISSUE THREAD

**Issue by andreaskarman** [Automattic/VIP-Coding-Standards#703]
## Bug Description

When setting "WordPress-VIP-Go" or "WordPressVIPMinimum" as PHPCS Standard, I get an error related to VariableAnalyses. I can use VariableAnalyses directly as a standard in PHPCS without any problems.

## Minimal Code Snippet

```php
phpcs: Cannot declare class VariableAnalysis\Sniffs\CodeAnalysis\VariableAnalysisSniff, because the name is already in use in /Users/xxx/.composer/vendor/sirbrillig/phpcs-variable-analysis/VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php on line 14
```
## Environment

| Question                | Answer
| ------------------------| -------
| PHP version             | 8.0.12
| PHP_CodeSniffer version | 3.6.1
| VIPCS version           | 2.3.3

## Tested Against `master` branch?

- [X] I have verified the issue still exists in the `master` branch of VIPCS.
- [X] I have verified the issue still exists in the `develop` branch of VIPCS.

**Comment by jrfnl** [comment]
@andreaskarman Hiya, I'd like to try and reproduce the issue, but need more information for that, so would you mind answering the following questions ? (and I may still have more questions after that)

1. How did you install VIPCS ? Via Composer ? Global, project local ? Git clone ?
2. How did you install VariableAnalysis ? Via VIPCS as a dependency ? Separately via Composer ? Global, project local ? Git clone ?
3. How are you running PHPCS ? What is the command used and from which directory ?
4. What does `phpcs -i` show when you run it with the same base command and from the same directory ?
5. May not be relevant, but still: what OS are you running on ?

I suspect there may be multiple PHPCS installs on your system and that the install being used to run PHPCS may not correspond to the install you _want_ to use. Sorry, I know that sounds a bit circumspect, but I can try to help you debug further when I know more.

**Comment by andreaskarman** [comment]
Thanks for the fast reply @jrfnl. Thanks!

By using your questions as a guideline, I managed to solve it. I had a two PPHPCS-instances. By reinstalling PHPCS with Homebrew and then use that one I managed get it working.

**Comment by jrfnl** [comment]
@andreaskarman Happy to be your rubber ducky ;-)
