### ISSUE TITLE
Update PHPUnit dependencies 

### ISSUE THREAD

**Issue by anigeluk** [Automattic/VIP-Coding-Standards#718]
https://github.com/Automattic/VIP-Coding-Standards/blob/796580706adaaf73a3a40e4c92a64dc9aaa0b700/composer.json#L29

We've had a customer report an issue with the PHPUnit version requirements in composer. Where up to version ^7 is required PHP 7 is required. 

They are trying to update to PHP8 which then fails the dependency as PHPUnit ^7 depends on PHP 7 

Can we please add ^8 

Thanks

**Comment by jrfnl** [comment]
As there has been no additional information provided, I'm presuming this issue can be closed.

Note: while widening the supported PHPUnit version wouldn't solve the above reported issue anyway, it should be possible to do so once squizlab/PHP_CodeSniffer#3803 has been merged, but there is no timeline available for when that will be.
