### ISSUE TITLE
End restricting usage of `term_exists()`

### ISSUE THREAD

**Issue by Chouby** [Automattic/VIP-Coding-Standards#720]
## What problem would the enhancement address for VIP?
Since WP 6.0.0, `term_exists()` uses `get_terms()` internally`. See https://core.trac.wordpress.org/ticket/36949. This means that reporting this function as not being cached is not true anymore.

## Describe the solution you'd like

WordPressVIPMinimum coding standards could stop reporting `terms_exists()` as a restricted function.

**Comment by GaryJones** [comment]
Hi @Chouby - good catch!

Looking at the code [here](https://github.com/Automattic/VIP-Coding-Standards/blob/e1eb7c9dbf93ebcbb20a610c6babe4b74725551d/WordPressVIPMinimum/Sniffs/Functions/RestrictedFunctionsSniff.php#L107-L113), VIPCS does mark the `term_exists()` function usage as an PHPCS Error.

We still have some VIP customers using WP < 6.0, so we wouldn't be able to remove the code entirely just yet, but we can certainly update the messaging to be more accurate.

**Comment by benlk** [comment]
It's good to see that this has been fixed in the upstream VIP PHPCS rules. How long until @wpcomvip-vipgoci-bot starts using the updated standards? It flagged a bunch of `term_exists` calls in a PR just today.

**Comment by GaryJones** [comment]
https://github.com/Automattic/vip-go-ci/releases/tag/1.3.12 includes an update to use VIPCS 3.0.1, which is the version which incorporates #812.

This was made available on customer repositories yesterday.

If you're finding it's still getting flagged, please open a support ticket with VIP, so we can look at your specific code and the feedback on your private repo.
