### ISSUE TITLE
Test supported PHPCSUtils versions via unit-tests workflow

### ISSUE THREAD

**Issue by GaryJones** [Automattic/VIP-Coding-Standards#743]
From https://github.com/Automattic/VIP-Coding-Standards/pull/734#discussion_r1059247674.

## What problem would the enhancement address for VIP?
With PHPCSUtils now being added as a dependency (#734), we should have confidence that the versions we claim to require will provide the behaviour we expect it to in sniffs.

## Describe the solution you'd like
It should it be added to the `unit-tests.yml` matrix? Or maybe the matrix/workflow should be changed to make use of the Composer `--prefer-lowest` / `--prefer-highest` options to simplify the maintenance of the version combinations?

**Comment by jrfnl** [comment]
Closing as fixed via #787 (sorry, only just now seeing there's an issue open for this)
