### ISSUE TITLE
WPCS: 3.0 merge_custom_array()

### ISSUE THREAD

**Issue by GaryJones** [Automattic/VIP-Coding-Standards#744]
## Bug Description

The `Sniff::merge_custom_array()` function was moved to a new Helper class in WPCS: https://github.com/WordPress/WordPress-Coding-Standards/pull/2157. 

As per https://github.com/Automattic/VIP-Coding-Standards/pull/734#discussion_r1059245439, it could still be used from WPCS, so the references (currently only 1) need updating when getting compatibility with 3.0.

## Minimal Code Snippet

See https://github.com/Automattic/VIP-Coding-Standards/blob/8953e4a7466288ec61670ef46b86556b605b7f88/WordPressVIPMinimum/Sniffs/AbstractVariableRestrictionsSniff.php#L130

## Environment

Use `php -v` and `composer show` to get versions.

| Question                | Answer
| ------------------------| -------
| PHP version             | N/A
| PHP_CodeSniffer version | N/A
| VIPCS version           | dev-develop / 3.0.0

**Comment by jrfnl** [comment]
Closing as fixed via #779
