### ISSUE TITLE
Test against PHP 8.2, and maybe 8.3

### ISSUE THREAD

**Issue by GaryJones** [Automattic/VIP-Coding-Standards#745]
## What problem would the enhancement address for VIP?
PHP 8.2 is released, and we should check how VIPCS works with it, even though WordPress itself doesn't yet support PHP 8.2.

## Describe the solution you'd like
Add `8.2` to the `test.yml` matrix. We'll also want to use `dev-develop` version of WPCS as well.

Also, add `8.3` as an `include`, but allow it to be experimental.

**Comment by jrfnl** [comment]
💯  Was thinking the same yesterday when reviewing #742, but didn't want to pollute the issue with unrelated remarks.

**Comment by jrfnl** [comment]
Notes about PHPCS vs 8.2:
* PHP 8.2 doesn't introduce a huge amount of syntax changes, so is nowhere near as problematic as some of the previous PHP releases.
* PR to support readonly classes is open and expected to be merged in PHPCS 3.8.0.
* Follow up PR to add support for readonly classes to various sniffs has been prepared.
* Big "still to do": add Tokenizer support for DNF (mixing intersection and union types and using parentheses in types - will probably mean that a new `T_OPEN_TYPE_PARENS` token will need to be introduced (and similar for close parens).
