### ISSUE TITLE
Ignore `locate_template()` in include sniff

### ISSUE THREAD

**Issue by philipjohn** [Automattic/VIP-Coding-Standards#80]
The `IncludingFile` sniff reports this

> File inclusion using custom constant (locate_template). Probably needs manual inspection.

for code like this

`include( locate_template('index-loop.php') );`

Obviously `locate_template()` isn't a constant, for a start. But it should probably be considered fine, because we know it's only searching for files located within specific directories, and therefore isn't going to be grabbing anything it shouldn't.

Thoughts?

**Comment by tomjn** [comment]
A +1 from here
