### ISSUE TITLE
Migrate to PHPCSStandards/PHP_CodeSniffer

### ISSUE THREAD

**Issue by kevinfodness** [Automattic/VIP-Coding-Standards#806]
## What problem would the enhancement address for VIP?
Per https://github.com/squizlabs/PHP_CodeSniffer/issues/3932, the `squizlabs/php_codesniffer` package is being abandoned in favor of `phpcsstandards/php_codesniffer`. The VIP Coding Standards package depends on the `squizlabs` version and should be migrated to the `phpcsstandards` version.

## Describe the solution you'd like

Replace the `squizlabs/php_codesniffer` dependency with `phpcsstandards/php_codesniffer` at version `3.8.0` (or whatever is current at time of implementation).

**Comment by kevinfodness** [comment]
This will be fixed by #805

**Comment by jrfnl** [comment]
@kevinfodness Please actually read the announcement and the [release notes of the 3.8.0 release](https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/tag/3.8.0):

> * For Composer users, **nothing changes**.
>      _In contrast to earlier information, the `squizlabs/php_codesniffer` package now points to the new repository and everything will continue to work as before._


The `phpcsstandards/php_codesniffer` package name should **NOT** be used and, if possible, will be removed from Packagist as soon as all other people who didn't read have migrated back to `squizlabs/php_codesniffer`.

**Comment by kevinfodness** [comment]
@jrfnl I apologize, I was acting on outdated information. I read the announcement when it came out, but it seems that the announcement was updated to indicate that changes to Composer installations were no longer required, and I (clearly) didn't read the release notes for v3.8.0. I had updated my fork of this repo and was in the process of creating a PR when I noticed that you already had one started. I appreciate how big of an undertaking this is, and simply wanted to help.

**Comment by jrfnl** [comment]
@kevinfodness I appreciate the intent. The news that the package name could be retained came a few days after the announcement and before the 3.8.0 release. This news was very welcome as it saves a ton in support issues, but, obviously, it also means that I now need to guard against people acting on outdated information.
