### ISSUE TITLE
checkForThisWithinClass when using Traits.

### ISSUE THREAD

**Issue by rheinardkorf** [Automattic/VIP-Coding-Standards#83]
Sniffing for the use of $this works great when in a `class` obviously. However, we have started to use Traits in some of our code. 

Could we we add checking for $this in a `trait` as well?

**Comment by rheinardkorf** [comment]
This could be as easy as changing 

```if ($scopeCode === T_CLASS) {```

in WordPressVIPMinimum_Sniffs_Variables_VariableAnalysisSniff::checkforThisWithinClass() to read:

```if (($scopeCode === T_CLASS) || ($scopeCode === T_TRAIT)) {```

**Comment by david-binda** [comment]
Thanks for the report @rheinardkorf ! It should be addressed via #111 . Feel free to reopen if you are experiencing some more issues.
