### ISSUE TITLE
Flag inappropriate usage of wp_enqueue_style() and wp_enqueue_script() 

### ISSUE THREAD

**Issue by gudmdharalds** [Automattic/VIP-Coding-Standards#84]
`wp_enqueue_style()` and `wp_enqueue_script()` are often not used correctly: sometimes the third argument ($deps) is assigned to `null` or `false`, for instance.  We should flag any calls to these functions using incorrect variable-types as arguments.

**Comment by david-binda** [comment]
I don't think this should be a concern. In https://core.trac.wordpress.org/browser/tags/4.9/src/wp-includes/class-wp-dependency.php#L77 the `$deps` argument is casted to array and thus such usage should not cause any harm.

I'm going to mark this as WONTFIX and close it for now, but feel free to reopen it in case there is some situation in which such usage causes any issues - eg.: produces PHP Warnings.
