### ISSUE TITLE
Catch incomplete escaping

### ISSUE THREAD

**Issue by gudmdharalds** [Automattic/VIP-Coding-Standards#88]
A fairly common strategy is the following:

`<a href="<?php echo esc_url(site_url()); ?>/about/"> ... </a>`

but it should be:

`<a href="<?php echo esc_url(site_url() . '/about/' ); ?>"> ... </a>`

Our ruleset should flag these.

**Comment by grappler** [comment]
As `about` is hardcoded I don't see why this would need to be escaped.

Though moving `'/about/'` as a parameter may be better.
`<a href="<?php echo esc_url(site_url( '/about/' ) ); ?>"> ... </a>`

**Comment by david-binda** [comment]
@gudmdharalds I also don't think we should be requiring developer to include whole URL in `esc_url` function in the example you provided, as I don't see how it could be causing any issues.

Could you, please, elaborate on what, security or any other, issue the suggested approach addresses over the "common strategy"?

**Comment by GaryJones** [comment]
If the strategy @gudmdharalds suggested is needed (it makes sense to me, and I've done it, but I've not yet found a use case that broke if it wasn't done), then this would be better to go into WPCS.

**Comment by GaryJones** [comment]
Closing for lack of feedback. Can be re-opened if feedback arrives and it's still something that should be flagged.
