### ISSUE TITLE
PHPCS 3.x Compatibility issue

### ISSUE THREAD

**Issue by emgk** [Automattic/VIP-Coding-Standards#89]
When I run the command.

> phpcs --standard=WordPressVIPMinimum test.php 

This below error comes up.

> PHP Fatal error:  Interface 'PHP_CodeSniffer_Sniff' not found in /usr/share/php/PHP/CodeSniffer/Standards/WordPressVIPMinimum/Sniffs/Constants/ConstantRestrictionsSniff.php on line 14

As the https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/ is now compatible with PHPCS 3.x. This repo should be compatible with the PHPCS 3.x

**Environment:**
PHPCS: 3.0.2
WPCS: develop branch

**Comment by grappler** [comment]
@emgk WPCS version 0.13.0 is PHPCS 3.0 compatible which is not yet released but will be this week.

**Comment by david-binda** [comment]
Hey @emgk !

The latest master branch, or anything since https://github.com/Automattic/VIP-Coding-Standards/releases/tag/0.2.0 should be PHPCS 3.x and WPCS 0.13.x compatible.

Please, let us know in case you are still hitting any issues.

**Comment by tomjn** [comment]
Everything's working alright here with phpcs 3.0.2 on VVV with the latest version of this and the WP coding standards, feel free to comment if it's still an issue after updating things and I'll reopen
